env:
  browser: true
  es6: true
extends:
  eslint:recommended
globals:
  Cesium: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  space-infix-ops: error
  no-unused-vars: [error, {vars: all, args: none}]
