default:
  image: node:12

stages:
  - setup
  - test
  - build
  - deploy

npm_install:
  stage: setup
  script:
    - npm ci
    - npm rm webpack
    - npm rm webpack-cli
    - npm rm webpack-dev-server
    - npm rm copy-webpack-plugin
    - npm rm speed-measure-webpack-plugin
    - npm rm mini-css-extract-plugin
    - npm rm css-loader
    - npm rm file-loader
    - du -sh node_modules/
  artifacts:
    paths:
      - node_modules/
    expire_in: 30m

pipeline_ok:
  stage: test
  script: tests/test_gitlab_deploy.sh

lint:
  stage: test
  script: npm run lint

build:
  stage: build
  script: RELEASE_NAME=$CI_COMMIT_REF_NAME npm run build
  artifacts:
    paths:
      - dist/
    expire_in: 30d

deploy_to_s3:
  stage: deploy
  image: python:latest
  script:
  - pip install awscli
  - scripts/gitlab_deploy.sh

add_link_for_reviews:
 stage: setup
 script: scripts/gitlab_add_link_for_reviews.sh
 only: [merge_requests]
