default:
  image: node:12

stages:
  - setup
  - test
  - setup_environment
  - build
  - deploy
  - sentry_deploy

npm_install:
  stage: setup
  script: npm ci
  artifacts:
    paths:
      - node_modules/
    expire_in: 30m

pipeline_ok:
  stage: test
  script: tests/test_gitlab_deploy.sh && tests/test_deploy_to_s3.sh

lint:
  stage: test
  script: npm run lint

build:
  stage: build
  script: npm run build
  artifacts:
    paths:
      - dist/
    expire_in: 30d

deploy_to_s3:
  stage: deploy
  image: python:latest
  script:
  - pip install awscli
  - scripts/gitlab_deploy.sh

add_link_for_reviews:
 stage: setup
 script: scripts/gitlab_add_link_for_reviews.sh
 only: [merge_requests]

setup_environment:
 stage: setup_environment
 script: CI_COMMIT_REF_NAME=$CI_COMMIT_REF_NAME node scripts/environment.js $CI_COMMIT_REF_NAME

deploy_sentry_sourcemaps:
 stage: sentry_deploy
 script: node scripts/deploySentrySourcemaps.js
