default:
  image: node:12

stages:
  - setup
  - test
  - build


npm_install:
  stage: setup
  script: npm ci
  artifacts:
    paths:
      - node_modules/
    expire_in: 30m

lint:
  stage: test
  script: npm run lint

typecheck:
  stage: test
  script: npm run typecheck


build:
  stage: build
  script: npm run build
