# https://www.serverless.com/framework/docs/providers/aws/guide/serverless.yml/

service: serverless-swissgeol

package:
  exclude:
    - ./**
  include:
    - lambda/**

plugins:
  - serverless-python-requirements
  - serverless-offline

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: us-west-2
  apiName: shortlink-api
  environment:
    S3_BUCKET: 'serverless-swissgeol-dev-serverlessdeploymentbuck-7r1g98ijhjng'
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 's3:PutObject'
        - 's3:GetObject'
      Resource: 'arn:aws:s3:::serverless-swissgeol-dev-serverlessdeploymentbuck-7r1g98ijhjng/u/*'

functions:
  urlRedirector:
    memorySize: 384
    package:
      include:
        - lambda/URLShortener/URLRedirector.py
    handler: lambda/URLShortener/URLRedirector.handler
    events:
      - http:
          path: /{key}
          method: get
          integration: lambda
          response:
            statusCodes:
              302:
                pattern: ''
                headers:
                  Location: integration.response.body.Redirect
  urlShortener:
    memorySize: 384
    package:
      include:
        - lambda/URLShortener/URLShortenet.py
    handler: lambda/URLShortener/URLShortener.handler
    events:
      - http:
          path: url_shortener
          method: post
          integration: lambda
          request:
            template:
              application/x-www-form-urlencoded: null
              application/json: null
            passThrough: WHEN_NO_MATCH
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
