name: CI

on:
  push:
    branches:
      - master
    tags:
      - test*
  pull_request:
    branches:
      - master
      - next-prod

env:
  IN_CI: "1"

jobs:
  build:
    runs-on: ubuntu-18.04
    timeout-minutes: 12

    steps:
      - run: export

      - uses: actions/checkout@v2

      - name: Setup
        run: |
          npm ci && du -sh node_modules
          THE_GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} scripts/github_add_link_for_reviews.sh

      - name: Lint
        run: npm run lint

      - name: Build
        env:
          RELEASE_NAME: ${scripts/get_github_name.sh}
        run: npm run build

      - name: Deploy to S3
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        run: |
          pip install awscli
          scripts/github_deploy.sh
